services:
#    debian-dockerize:

#    dns:
#        command: "/bin/bash -c 'env; sleep 1h'"

    jekyll:
        command: "/bin/bash -c 'env; sleep 1h'"

    jekyll-dev:
        volumes:
            - ./:/srv/jekyll:rw
        command: "/bin/bash -c 'env; sleep 1h'"

    nginx-http:
        command: "/bin/bash -c 'env; sleep 1h'"

    nginx-https:
        command: "/bin/bash -c 'env; sleep 1h'"

    letsencrypt:
        command: "/bin/bash -c 'env; sleep 1h'"

    isso:
        command: "/bin/bash -c 'env; sleep 1h'"

    challenges:
        command: "/bin/bash -c 'env; sleep 1h'"

    syncthing:
        command: "/bin/bash -c 'env; sleep 1h'"
        ports:
            - 127.0.0.1:8384:8384

    volume-sync:
        command: "/bin/bash -c 'env; sleep 1h'"

